import type { WikiArticle } from "@/types/wiki";

export const wikiArticlesPl: WikiArticle[] = [
  {
    id: "what-is-phishing",
    title: "Co to jest phishing?",
    category: "phishing",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Phishing to atak oparty na inżynierii społecznej, w którym przestępcy podszywają się pod zaufane marki, aby wykradać hasła, dane płatnicze lub kody MFA.",
    howItWorks: ["Fałszywe e-maile", "Fałszywe strony logowania", "Presja psychologiczna", "Pilne komunikaty"],
    examples: [
      "Fałszywy e-mail „weryfikacji” PayPal",
      "Podszywana pod Microsoft 365 strona logowania",
      "Wiadomość typu „Twoje konto zostanie zawieszone”",
    ],
    redFlags: ["Podejrzane domeny", "Literówki", "Groźby i pilność", "Nieoczekiwane załączniki"],
    preventionTips: ["Weryfikuj nadawcę", "Najedź na link (bez klikania)", "Używaj MFA", "Nigdy nie udostępniaj haseł"],
    relatedTopics: ["Phishing wymierzony (spear)", "Smishing", "Kompromitacja poczty firmowej (BEC)", "Dobre praktyki MFA"],
  },
  {
    id: "password-security-fundamentals",
    title: "Podstawy bezpieczeństwa haseł",
    category: "password-security",
    readingTime: "7 min czytania",
    dangerLevel: "Medium",
    description:
      "Silne, unikalne hasła, menedżery haseł i MFA są niezbędne, aby blokować przejmowanie kont i ataki credential stuffing.",
    howItWorks: [
      "Atakujący wykorzystują wycieki haseł",
      "Boty testują ponownie użyte dane na masową skalę",
      "Słabe hasła łamie się szybko",
      "MFA blokuje wiele automatycznych przejęć",
    ],
    examples: ["Słabe hasło: password123", "Średnie hasło: Summer2024!", "Silne hasło: Q7#fP2!mL9@t"],
    redFlags: ["Powtarzane hasła", "Brak MFA", "Brak menedżera haseł", "Hasła przez czat"],
    preventionTips: [
      "Stosuj długie, unikalne frazy hasłowe",
      "Przechowuj sekrety w menedżerze haseł",
      "Włącz MFA w krytycznych usługach",
      "Natychmiast zmień skompromitowane dane logowania",
    ],
    relatedTopics: ["Credential stuffing", "Klucze dostępu (passkeys)", "Przejęcie sesji", "Zmęczenie MFA"],
  },
  {
    id: "malware-overview",
    title: "Przegląd złośliwego oprogramowania",
    category: "malware",
    readingTime: "8 min czytania",
    dangerLevel: "Critical",
    description:
      "Malware to złośliwe oprogramowanie mające kraść dane, szpiegować użytkowników, uszkadzać systemy lub szyfrować pliki w celu okupu.",
    howItWorks: ["Infekcja przez e-mail lub pobranie", "Wykonanie ładunku", "Mechanizm persystencji", "Kradzież lub szyfrowanie danych"],
    examples: ["Ransomware blokujący pliki firmy", "Koń trojański w crackowanym oprogramowaniu", "Spyware zbierający sesje przeglądarki"],
    redFlags: ["Nagły spadek wydajności", "Nieznane programy startowe", "Nieoczekiwany ruch wychodzący", "Niedostępność plików"],
    preventionTips: ["Szybko aktualizuj systemy", "Używaj ochrony endpointów", "Unikaj niezaufanych plików wykonywalnych", "Trzymaj kopie zapasowe offline"],
    relatedTopics: ["Reakcja na ransomware", "EDR", "Eksploity zero-day", "Sandboxing"],
  },
  {
    id: "ai-scams-deepfakes",
    title: "Oszustwa AI i deepfake’i",
    category: "ai-threats",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Sztucznie generowany głos, wideo i treści mogą służyć do podszywania się pod zaufane osoby oraz wywoływania fraudu lub wycieku danych.",
    howItWorks: ["Klonowanie głosu z krótkiego nagrania", "Podszywanie wideo (deepfake)", "Phishingowe wiadomości z AI", "Syntetyczne tożsamości w sieci"],
    examples: [
      "Fałszywy głos „prezesa” z żądaniem pilnego przelewu",
      "Deepfake rozmowy „wsparcia” proszący o OTP",
      "Mail „HR” wygenerowany przez AI z malware w załączniku",
    ],
    redFlags: ["Pilność od znajomej osoby", "Dziwna składnia lub timing", "Prośby o pominięcie procedur płatności", "Brak alternatywnej weryfikacji"],
    preventionTips: ["Weryfikacja oddzwonieniem", "Podwójna akceptacja przelewów", "Wewnętrzne hasła awaryjne", "Szkolenia z sygnałów deepfake"],
    relatedTopics: ["BEC", "Vishing", "Podszywanie tożsamości", "Kontrole antyfraudowe"],
  },
  {
    id: "browser-security-basics",
    title: "Podstawy bezpieczeństwa przeglądarki",
    category: "web-security",
    readingTime: "6 min czytania",
    dangerLevel: "Medium",
    description:
      "Przeglądarki to poważna powierzchnia ataku. Bezpieczne ustawienia i higiena rozszerzeń ograniczają drive-by i nadużycia śledzenia.",
    howItWorks: [
      "Złośliwe skrypty w kontekście przeglądarki",
      "Ryzykowne rozszerzenia wyciekają dane",
      "Skompromitowane sesje mogą zostać przejęte",
      "Strony phishingowe udają znane aplikacje",
    ],
    examples: ["Rozszerzenie żądające nadmiarowych uprawnień", "Kradzież ciasteczka sesji na niezabezpieczonym urządzeniu", "Łańcuchy przekierowań z malvertisingu"],
    redFlags: ["Nieznane rozszerzenia", "Nieoczekiwane przekierowania", "Ostrzeżenia certyfikatu", "Automatyczne pobieranie"],
    preventionTips: ["Aktualizuj przeglądarkę", "Tylko zaufane rozszerzenia", "Włącz ochronę bezpiecznego przeglądania", "Unikaj logowania na współdzielonych urządzeniach"],
    relatedTopics: ["XSS", "Bezpieczeństwo sesji", "TLS", "Ochrona przed śledzeniem"],
  },
  {
    id: "remote-work-security",
    title: "Bezpieczeństwo pracy zdalnej",
    category: "workplace-security",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Rozproszone zespoły są atakowane przez słabe endpointy, shadow IT i phishing. Jasne kontrole ograniczają ekspozycję organizacji.",
    howItWorks: ["Skompromitowane niezarządzane urządzenia", "Dostęp z niebezpiecznej sieci domowej", "Kradzież danych logowania na prywatnych narzędziach", "Nieweryfikowane udostępnianie plików"],
    examples: ["Wrażliwe dokumenty w prywatnej chmurze", "Phishing poświadczeń VPN przez fałszywy portal", "Otwarty RDP z routera domowego"],
    redFlags: ["Nieznane urządzenia", "Brak szyfrowania dysku", "Omijanie VPN", "Uprawnienia administratora na kontach codziennych"],
    preventionTips: ["Wymuszaj zarządzane endpointy", "MFA i SSO", "Zasada najmniejszych uprawnień", "Ciągły audyt dostępu zdalnego"],
    relatedTopics: ["Zero trust", "Bezpieczeństwo endpointów", "Zarządzanie dostępem", "DLP"],
  },
  {
    id: "mobile-phishing",
    title: "Phishing mobilny",
    category: "mobile-security",
    readingTime: "5 min czytania",
    dangerLevel: "High",
    description:
      "Atakujący nadużywają SMS, komunikatorów i powiadomień mobilnych, aby kraść dane logowania i kody jednorazowe.",
    howItWorks: ["Fałszywy SMS kurierski lub bankowy", "Złośliwe skrócone linki", "Fałszywe monity aktualizacji aplikacji", "Przepływy wyłudzające OTP"],
    examples: ["Fałszywy link kuriera z prośbą o kartę", "Podszyty alert banku w komunikatorze", "Kradzież logowania przez kod QR"],
    redFlags: ["Skrócone linki", "Pilność w SMS", "Nieoczekiwana prośba o instalację aplikacji", "Prośby o kod MFA"],
    preventionTips: ["Nie ufaj linkom z niechcianych SMS", "Tylko oficjalne sklepy z aplikacjami", "Blokada SIM", "Szybko zgłaszaj podejrzenia"],
    relatedTopics: ["Smishing", "SIM swap", "Bezpieczeństwo MFA", "Malware mobilny"],
  },
  {
    id: "cloud-shared-responsibility",
    title: "Model współdzielonej odpowiedzialności w chmurze",
    category: "cloud-security",
    readingTime: "5 min czytania",
    dangerLevel: "Medium",
    description:
      "Bezpieczeństwo chmury jest podzielone: dostawca zabezpiecza infrastrukturę, klient — tożsamości, dane i konfiguracje.",
    howItWorks: [
      "Dostawca zabezpiecza warstwy fizyczne i środowiska",
      "Klient zabezpiecza IAM i dostęp do danych",
      "Błędna konfiguracja odsłania zasoby",
      "Słabe klucze umożliwiają ruch horyzontalny",
    ],
    examples: ["Publiczny magazyn obiektów z rekordami", "Nadmiernie uprzywilejowane konta serwisowe", "Klucze API chmury na sztywno w repozytorium"],
    redFlags: ["Publiczne buckety", "Brak rotacji kluczy", "Brak logów audytowych", "Nadmierna liczba ról admin"],
    preventionTips: ["IAM według najmniejszych uprawnień", "Scentralizowane ślady audytu", "Skanuj IaC pod kątem błędów", "Rotuj i przechowuj sekrety w sejfie"],
    relatedTopics: ["IAM", "CSPM", "Zarządzanie sekretami", "Klasyfikacja danych"],
  },
  {
    id: "online-privacy-basics",
    title: "Podstawy prywatności w sieci",
    category: "privacy",
    readingTime: "5 min czytania",
    dangerLevel: "Medium",
    description:
      "Cyfrowa prywatność ogranicza kradzież tożsamości i ukierunkowany fraud przez redukcję niepotrzebnego ujawniania danych.",
    howItWorks: ["Trackery zbierają zachowanie między stronami", "Brokery danych agregują rekordy", "Nadmierne udostępnianie ujawnia odpowiedzi zabezpieczeń", "Wyciek metadanych ujawnia nawyki"],
    examples: ["Metadane lokalizacji w zdjęciach", "Publiczny profil z datą urodzenia", "Trackery profilujące zachowanie"],
    redFlags: ["Szerokie uprawnienia aplikacji", "Publiczne dane osobowe", "Nieznani brokerzy danych", "Ciągłe śledzenie reklam"],
    preventionTips: ["Przeglądaj ustawienia prywatności co miesiąc", "Antyśledzenie w przeglądarce", "Minimalizuj udostępnianie danych", "Unikalne adresy e-mail do usług"],
    relatedTopics: ["Kradzież tożsamości", "OSINT", "Blokowanie trackerów", "Regulacje prywatności"],
  },
  {
    id: "social-engineering-basics",
    title: "Podstawy inżynierii społecznej",
    category: "social-engineering",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Inżynieria społeczna manipuluje zaufaniem, strachem i poczuciem pilności, aby ominąć techniczne zabezpieczenia przez zachowanie ludzi.",
    howItWorks: ["Szybkie budowanie fałszywego zaufania", "Wyzwolenie pilności lub strachu", "Prośba o wrażliwą czynność", "Wykorzystanie autorytetu"],
    examples: ["Fałszywe IT proszące o kod resetu", "„Prezes” żądający pilnego przelewu", "Wślizgnięcie się (tailgating) do strefy chronionej"],
    redFlags: ["Nietypowa pilność", "Ominięcie procesu", "Rozbieżność tożsamości", "Presja, by unikać weryfikacji"],
    preventionTips: ["Weryfikacja na osobnym kanale", "Ścisłe procesy akceptacji", "Szkolenia z symulacjami", "Nagradzanie zgłaszania podejrzeń"],
    relatedTopics: ["Phishing", "BEC", "Ryzyko insidera", "Świadomość bezpieczeństwa"],
  },
  {
    id: "network-segmentation",
    title: "Segmentacja sieci",
    category: "network-security",
    readingTime: "7 min czytania",
    dangerLevel: "High",
    description:
      "Segmentacja ogranicza ruch horyzontalny po kompromitacji, izolując systemy, użytkowników i usługi w strefach zaufania.",
    howItWorks: [
      "Twórz strefy wg wrażliwości",
      "Ścisłe zasady ruchu east-west",
      "Reguły zapory między segmentami",
      "Monitoruj nietypowy ruch między segmentami",
    ],
    examples: ["Izolacja baz produkcyjnych od VLAN użytkowników", "Osobna sieć adminów", "Wi-Fi gości odcięte od usług firmowych"],
    redFlags: ["Płaska sieć", "Reguły „dozwól wszystko”", "Brak monitorowania wewnętrznego", "Wspólne ścieżki adminów"],
    preventionTips: ["Segmentacja w stylu zero trust", "Domyślna odmowa", "Regularny przegląd reguł", "Alerty na podejrzany ruch horyzontalny"],
    relatedTopics: ["Polityka zapory", "Zero trust", "NAC", "Wykrywanie ruchu horyzontalnego"],
  },
  {
    id: "incident-response-lifecycle",
    title: "Cykl reagowania na incydenty",
    category: "incident-response",
    readingTime: "8 min czytania",
    dangerLevel: "Critical",
    description:
      "Jasny cykl IR pozwala zespołom wykrywać, izolować, usuwać przyczynę i odtwarzać się po incydentach cyberbezpieczeństwa.",
    howItWorks: ["Przygotowanie i runbooki", "Wykrywanie i triage", "Izolacja i eliminacja", "Odtworzenie i lessons learned"],
    examples: ["Izolacja ransomware", "Dochodzenie po kompromitacji poświadczeń", "Reakcja na przejęcie konta chmurowego"],
    redFlags: ["Brak dyżurów", "Brak runbooków", "Opóźniona eskalacja", "Brak przeglądu po incydencie"],
    preventionTips: ["Ćwiczenia stołowe", "Zdefiniowany poziom ciężkości i właściciele", "Scentralizowane logi do triage", "Śledzenie działań naprawczych"],
    relatedTopics: ["Forensics", "Operacje SOC", "Komunikacja kryzysowa", "BCP/DR"],
  },
  {
    id: "identity-access-management",
    title: "Zarządzanie tożsamością i dostępem (IAM)",
    category: "identity-access",
    readingTime: "7 min czytania",
    dangerLevel: "High",
    description:
      "IAM kontroluje, kto ma dostęp do systemów i danych. Silne zarządzanie tożsamością to fundament współczesnego bezpieczeństwa.",
    howItWorks: ["Silne uwierzytelnianie", "Autoryzacja według najmniejszych uprawnień", "Przegląd i unieważnianie starych kont", "Ciągły audyt aktywności uprzywilejowanej"],
    examples: ["Przejęcie konta admina przez słabe MFA", "Konto byłego pracownika nadal aktywne", "Konto serwisowe z nadmiarem uprawnień"],
    redFlags: ["Współdzielone konta", "Brak przeglądów dostępu", "Stałe prawa admina", "Brak scentralizowanego SSO"],
    preventionTips: ["SSO i dostęp warunkowy", "Uprzywilejowanie typu just-in-time", "Automatyzacja onboard/offboard", "Audyt krytycznych ścieżek dostępu"],
    relatedTopics: ["PAM", "RBAC", "Zero trust access", "Identity governance"],
  },
  {
    id: "devsecops-foundations",
    title: "Podstawy DevSecOps",
    category: "devsecops",
    readingTime: "7 min czytania",
    dangerLevel: "Medium",
    description:
      "DevSecOps integruje bezpieczeństwo z pipeline’ami deweloperskimi, aby podatności wykrywać wcześnie.",
    howItWorks: ["Testy bezpieczeństwa „shift-left”", "Automatyczny SAST/DAST w CI", "Skan zależności i sekretów", "Polityki dla IaC"],
    examples: ["Blokada merge przy krytycznym CVE", "Wykryty klucz API w commicie", "Wdrożenie zatrzymane przez niebezpieczną IaC"],
    redFlags: ["Brak kontroli bezpieczeństwa w CI", "Nieprzypięte zależności", "Ignorowane krytyczne znaleziska", "Wyłącznie ręczne release’y"],
    preventionTips: ["Automatyczne bramki bezpieczeństwa", "Znaleziska jak element backlogu", "Podpisane artefakty", "Ciągłe aktualizacje zależności"],
    relatedTopics: ["Bezpieczeństwo łańcucha dostaw", "SAST", "DAST", "Bezpieczeństwo IaC"],
  },
  {
    id: "email-authentication",
    title: "Uwierzytelnianie poczty (SPF, DKIM, DMARC)",
    category: "email-security",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Standardy uwierzytelniania poczty ograniczają podszywanie i zwiększają odporność na phishing dla domen organizacji.",
    howItWorks: ["SPF waliduje serwery wysyłające", "DKIM podpisuje integralność", "DMARC określa politykę egzekwowania", "Raporty ujawniają próby podszywania"],
    examples: ["Podszyta domena zablokowana przez DMARC reject", "Kwarantanna przy nieudanym DKIM", "Raporty pokazujące nadużycie marki"],
    redFlags: ["Brak polityki DMARC", "Niespójny SPF/DKIM", "Duży wolumen raportów spoofingu", "Niezaufane zewnętrzne nadawcy"],
    preventionTips: ["Poprawnie opublikuj SPF, DKIM, DMARC", "DMARC najpierw w monitoringu, potem egzekwowanie", "Tygodniowy przegląd raportów agregowanych", "Inwentaryzacja zatwierdzonych nadawców"],
    relatedTopics: ["Ochrona przed phishingiem", "Ochrona marki", "Brama pocztowa", "Higiena domeny"],
  },
  {
    id: "iot-device-hardening",
    title: "Utwardzanie urządzeń IoT",
    category: "iot-security",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Urządzenia IoT często mają słabe ustawienia domyślne. Utwardzenie i segmentacja są kluczowe dla ryzyka kompromitacji.",
    howItWorks: ["Zmiana domyślnych haseł od razu", "Regularne aktualizacje firmware", "Izolacja IoT od sieci krytycznych", "Wyłączenie zbędnych usług"],
    examples: ["Botnet kamer z domyślnymi hasłami", "Czujnik na starej wersji firmware", "Panel admin IoT wystawiony do internetu"],
    redFlags: ["Domyślne hasła", "Brak ścieżki aktualizacji", "Panele urządzeń w internecie", "Brak izolacji sieciowej"],
    preventionTips: ["Inwentaryzacja IoT", "Dedykowany VLAN dla IoT", "Silne uwierzytelnianie i certyfikaty", "Monitorowanie nietypowego ruchu IoT"],
    relatedTopics: ["Bezpieczeństwo OT", "Segmentacja sieci", "Zarządzanie aktywami", "Bezpieczeństwo firmware"],
  },
  {
    id: "endpoint-protection-basics",
    title: "Podstawy ochrony endpointów",
    category: "endpoint-security",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Endpointy to główne wektory ataku. Warstwowa ochrona i monitoring zmniejszają skutki kompromitacji.",
    howItWorks: ["Monitorowanie podejrzanego zachowania procesów", "Baseline utwardzenia urządzeń", "Wykrywanie persystencji", "Szybka izolacja hostów"],
    examples: ["Zablokowany skrypt przez politykę EDR", "Skompromitowany laptop odcięty od sieci", "Alert na nieautoryzowaną aktywność PowerShell"],
    redFlags: ["Wyłączony agent endpoint", "Stare łatki OS", "Nieznane binaria", "Nieoczekiwane narzędzia adminów"],
    preventionTips: ["EDR/XDR ze scentralizowanymi alertami", "Szybkie łatanie OS", "Ograniczenie lokalnego admina", "Izolacja ryzykownych urządzeń"],
    relatedTopics: ["EDR", "Utwardzanie urządzeń", "IR", "Zarządzanie uprawnieniami"],
  },
  {
    id: "threat-intel-fundamentals",
    title: "Podstawy threat intelligence",
    category: "threat-intelligence",
    readingTime: "7 min czytania",
    dangerLevel: "Medium",
    description:
      "Threat intelligence pomaga rozumieć taktyki atakujących i priorytetyzować obronę na podstawie rzeczywistej aktywności.",
    howItWorks: ["Zbieranie wskaźników i raportów", "Korelacja z telemetrią wewnętrzną", "Priorytetyzacja detekcji i mitigacji", "Udostępnianie intel wewnątrz organizacji"],
    examples: ["Blokada domen powiązanych z aktywnymi zestawami phishingowymi", "Aktualizacja detekcji pod ransomware TTP", "Strojenie alertów pod kampanie branżowe"],
    redFlags: ["Nieweryfikowane feedy", "Brak kontekstu dla IOC", "Przestarzałe reguły", "Brak pętli zwrotnej"],
    preventionTips: ["Kuratowane źródła intel", "Mapowanie na MITRE ATT&CK", "Automatyzacja wzbogacania IOC", "Tygodniowy przegląd wpływu intel"],
    relatedTopics: ["Operacje SOC", "Inżynieria detekcji", "MITRE ATT&CK", "Procesy CTI"],
  },
  {
    id: "secure-coding-basics",
    title: "Podstawy bezpiecznego kodowania",
    category: "application-security",
    readingTime: "7 min czytania",
    dangerLevel: "High",
    description:
      "Bezpieczeństwo aplikacji zaczyna się od wzorców kodowania, walidacji wejścia oraz solidnego uwierzytelniania i autoryzacji.",
    howItWorks: ["Walidacja całego niezaufanego wejścia", "Bezpieczna sesja i uwierzytelnianie", "Najmniejsze uprawnienia w usługach aplikacji", "Ciągłe testy podatności"],
    examples: ["SQL injection przez parametryzowane zapytania", "Blokada XSS przez kodowanie wyjścia", "Naprawa niebezpiecznych bezpośrednich referencji do obiektów"],
    redFlags: ["Sekrety w kodzie", "Brak walidacji wejścia", "Słabe przepływy auth", "Brak testów bezpieczeństwa w CI"],
    preventionTips: ["Standardy bezpiecznego kodowania", "SAST/DAST w pipeline", "Skan podatności zależności", "Rotacja i sejf sekretów aplikacji"],
    relatedTopics: ["OWASP Top 10", "DevSecOps", "SAST", "Zarządzanie sekretami"],
  },
  {
    id: "encryption-basics",
    title: "Podstawy szyfrowania",
    category: "cryptography",
    readingTime: "6 min czytania",
    dangerLevel: "Medium",
    description:
      "Szyfrowanie chroni poufność w spoczynku i w transporcie. Poprawne zarządzanie kluczami jest równie ważne jak algorytmy.",
    howItWorks: ["Szyfrowanie symetryczne dla danych magazynowanych", "Kryptografia asymetryczna dla wymiany kluczy", "TLS dla danych w transporcie", "Rotacja i ochrona kluczy"],
    examples: ["Szyfrowanie pól bazy dla wrażliwych rekordów", "Certyfikaty TLS dla API", "Rotacja kluczy po wycieku"],
    redFlags: ["Słabe lub przestarzałe szyfry", "Klucze w repozytorium", "Przeterminowane certyfikaty", "Brak polityki rotacji kluczy"],
    preventionTips: ["Nowoczesne algorytmy i wersje TLS", "Klucze w dedykowanych menedżerach sekretów", "Regularna rotacja certyfikatów i kluczy", "Szyfrowanie kopii zapasowych i wrażliwych logów"],
    relatedTopics: ["TLS", "PKI", "Zarządzanie kluczami", "Ochrona danych"],
  },
  {
    id: "security-awareness-training",
    title: "Szkolenia z świadomości bezpieczeństwa",
    category: "security-awareness",
    readingTime: "5 min czytania",
    dangerLevel: "Medium",
    description:
      "Programy świadomościowe zmniejszają incydenty ludzkie poprzez praktyczne rozpoznawanie zagrożeń i nawyki reakcji.",
    howItWorks: ["Moduły wg ról", "Regularne symulacje phishingu", "Krótkie przypomnienia", "Śledzenie poprawy zachowań"],
    examples: ["Kwartalne kampanie symulacji phishingu", "Mikronauka o higienie haseł", "Ćwiczenia zgłaszania dla zespołów nietechnicznych"],
    redFlags: ["Jednoroczne szkolenie bez kontynuacji", "Brak symulacji", "Brak kultury zgłaszania", "Material nie dopasowany do roli"],
    preventionTips: ["Krótkie, częste sesje", "Materiał wg działów", "Nagradzanie wczesnego zgłaszania", "Mierzenie efektów, nie tylko ukończenia"],
    relatedTopics: ["Obrona przed phishingiem", "Inżynieria społeczna", "Zarządzanie ryzykiem ludzkim", "Kultura bezpieczeństwa"],
  },
  {
    id: "spear-phishing-targeted-attacks",
    title: "Phishing wymierzony (spear phishing)",
    category: "phishing",
    readingTime: "5 min czytania",
    dangerLevel: "High",
    description:
      "Spear phishing celuje w konkretne osoby spersonalizowanymi przynętami, aby ominąć ogólne kontrole świadomości.",
    howItWorks: ["Badanie ofiary", "Spersonalizowana złośliwa wiadomość", "Pilność i sygnały zaufania", "Kradzież poświadczeń lub malware"],
    examples: ["Fałszywy mail CFO z żądaniem pilnej płatności", "Spersonalizowany link „od HR”", "Fałszywa faktura dostawcy z prawdziwymi imionami"],
    redFlags: ["Szczegółowe, lecz nietypowe żądanie", "Domeny podszywające się", "Nieoczekiwane zmiany płatności", "Logowanie na zewnętrznych stronach"],
    preventionTips: ["Weryfikacja drugim kanałem", "Kontrole akceptacji płatności", "Szkolenia dla grup wysokiego ryzyka", "Phishingoodporne MFA"],
    relatedTopics: ["BEC", "Inżynieria społeczna", "Bezpieczeństwo poczty", "MFA"],
  },
  {
    id: "passkeys-passwordless-security",
    title: "Klucze dostępu i logowanie bez hasła",
    category: "password-security",
    readingTime: "6 min czytania",
    dangerLevel: "Low",
    description:
      "Passkeys ograniczają phishing i kradzież poświadczeń, zastępując hasła kryptograficznym uwierzytelnianiem.",
    howItWorks: ["Urządzenie tworzy parę kluczy", "Klucz prywatny pozostaje na urządzeniu", "Uwierzytelnianie przez podpisane wyzwanie", "Brak transmisji współdzielonego sekretu hasła"],
    examples: ["Logowanie biometrią urządzenia", "Logowanie między urządzeniami przez kod QR", "Spadek liczby resetów hasła"],
    redFlags: ["Brak kontroli odzyskiwania konta", "Współdzielone niezarządzane urządzenia", "Wyłącznie przestarzałe logowanie", "Brak zapasowej metody MFA"],
    preventionTips: ["Passkeys w krytycznych aplikacjach", "Bezpieczny proces odzyskiwania", "Połączenie z bezpieczeństwem urządzenia", "Edukacja użytkowników dotycząca rejestracji"],
    relatedTopics: ["FIDO2", "MFA", "Credential stuffing", "Bezpieczeństwo tożsamości"],
  },
  {
    id: "xss-attack-overview",
    title: "Cross-site scripting (XSS) — przegląd",
    category: "web-security",
    readingTime: "7 min czytania",
    dangerLevel: "High",
    description:
      "XSS pozwala atakującym wstrzykiwać skrypty na zaufane strony, co prowadzi do kradzieży sesji, przekierowań lub złośliwych działań.",
    howItWorks: ["Niesanityzowane wejście trafia do przeglądarki", "Wstrzyknięty skrypt wykonuje się w kontekście użytkownika", "Możliwy dostęp do ciasteczek/tokenów", "Przejęcie sesji lub działań"],
    examples: ["Wstrzyknięcie skryptu w polu komentarza", "Trwały payload w bio profilu", "Odbity skrypt w wyszukiwarce"],
    redFlags: ["Brak kodowania wyjścia", "Niebezpieczne renderowanie HTML", "Mnóstwo inline script", "Brak CSP"],
    preventionTips: ["Escapowanie niezaufanego wyjścia", "Content Security Policy", "Walidacja i sanityzacja wejścia", "Bezpieczne ustawienia frameworków"],
    relatedTopics: ["OWASP Top 10", "Przejęcie sesji", "CSP", "Bezpieczne kodowanie"],
  },
  {
    id: "ransomware-attacks",
    title: "Ataki ransomware",
    category: "malware",
    readingTime: "7 min czytania",
    dangerLevel: "Critical",
    description:
      "Ransomware szyfruje pliki i żąda okupu, często po wykradzeniu danych i eskalacji uprawnień.",
    howItWorks: ["Wejście przez phishing lub eksploit", "Eskalacja i ruch horyzontalny", "Ekfiltracja przed szyfrowaniem", "Szyfrowanie i notatka z żądaniem"],
    examples: ["Masowe szyfrowanie serwerów plików", "Podwójny szantaż z groźbą wycieku", "Usunięcie kopii zapasowych przed payloadem"],
    redFlags: ["Masowe zmiany nazw plików", "Wyłączone narzędzia bezpieczeństwa", "Nietypowe działania adminów", "Pliki z notatką okupu"],
    preventionTips: ["Niemułowe kopie offline", "Segmentacja i najmniejsze uprawnienia", "Łatanie krytycznych systemów", "Ćwiczenie scenariuszy IR"],
    relatedTopics: ["IR", "EDR", "Strategia kopii zapasowych", "Segmentacja sieci"],
  },
  {
    id: "deepfakes-explained",
    title: "Deepfake — wyjaśnienie",
    category: "ai-threats",
    readingTime: "6 min czytania",
    dangerLevel: "High",
    description:
      "Deepfake’y wykorzystują AI do fabrykowania realistycznych mediów dla fraudu, podszywania się i dezinformacji.",
    howItWorks: ["Zebranie próbek głosu/wideo", "Generacja syntetycznych mediów", "Osadzenie w kontekście społecznym lub biznesowym", "Presja pilności"],
    examples: ["Fałszywe wideo z akceptacją „prezesa”", "Sklonowany głos żądający przelewu", "Syntetyczna tożsamość w rozmowie „wsparcia”"],
    redFlags: ["Artefakty synchronizacji warg", "Nierówny rytm głosu", "Brak zweryfikowanej ścieżki oddzwonienia", "Wysokociśnieniowe żądania"],
    preventionTips: ["Weryfikacja poza pasmem", "Podwójna akceptacja płatności", "Szkolenia z deepfake", "Sprawdzanie pochodzenia mediów"],
    relatedTopics: ["Vishing", "Przeciwdziałanie fraudowi", "Podszywanie się", "Świadomość bezpieczeństwa"],
  },
  {
    id: "least-privilege-access-model",
    title: "Model najmniejszych uprawnień",
    category: "workplace-security",
    readingTime: "5 min czytania",
    dangerLevel: "Medium",
    description:
      "Najmniejsze uprawnienia ograniczają dostęp użytkowników i usług do niezbędnego minimum, zmniejszając promień kompromitacji.",
    howItWorks: ["Mapowanie dostępu wg roli", "Minimalne przyznane uprawnienia", "Harmonogramowy przegląd dostępu", "Szybkie odbieranie nieużywanych praw"],
    examples: ["Dostęp tylko do odczytu dla analityków", "Tymczasowe podwyższone role admina", "Automatyczne odebranie dostępu po projekcie"],
    redFlags: ["Stałe prawa administratora", "Współdzielone konta uprzywilejowane", "Brak rekertyfikacji dostępu", "Narastanie uprawnień (privilege creep)"],
    preventionTips: ["RBAC", "JIT dla podwyższenia uprawnień", "Audyt przypisań wrażliwych ról", "Automatyzacja onboard/offboard"],
    relatedTopics: ["IAM", "PAM", "Zero trust", "Ryzyko insidera"],
  },
  {
    id: "unsafe-mobile-apps",
    title: "Niebezpieczne aplikacje mobilne",
    category: "mobile-security",
    readingTime: "5 min czytania",
    dangerLevel: "Medium",
    description:
      "Złośliwe lub nadmiernie uprawnione aplikacje mogą eksfiltrować dane, śledzić użytkowników i osłabiać bezpieczeństwo urządzenia.",
    howItWorks: ["Aplikacja żąda nadmiaru uprawnień", "Zbiera kontakty/lokalizację/wiadomości", "Wysyła dane na zdalne serwery", "Może instalować ukryte moduły"],
    examples: ["Latarka z dostępem do SMS", "Fałszywy bank w nieoficjalnym sklepie", "Adware z ukrytą usługą w tle"],
    redFlags: ["Niepotrzebne uprawnienia", "Słaba reputacja dewelopera", "Propozycje APK poza sklepem", "Nagły spadek baterii lub skok transferu"],
    preventionTips: ["Instalacje tylko ze zaufanych sklepów", "Przegląd uprawnień", "Aktualny OS", "Ochrona mobilna przed zagrożeniami"],
    relatedTopics: ["Malware mobilny", "Smishing", "Uprawnienia aplikacji", "Utwardzanie urządzenia"],
  },
  {
    id: "cloud-data-exposure",
    title: "Ujawnienie danych w chmurze",
    category: "cloud-security",
    readingTime: "5 min czytania",
    dangerLevel: "High",
    description:
      "Błędna konfiguracja magazynów i polityk tożsamości to częsta przyczyna masowych wycieków wrażliwych danych.",
    howItWorks: ["Przypadkowe publiczne udostępnienie", "Zbyt szerokie IAM", "Wycieki kluczy API z repozytoriów", "Słabe monitorowanie opóźnia wykrycie"],
    examples: ["Publiczny bucket z PII klientów", "Klucz API admina w repozytorium", "Otwarty snapshot ze zrzutem bazy"],
    redFlags: ["Publiczny odczyt/zapis", "Brak barier IAM", "Brak wymuszania szyfrowania", "Brak alertów audytowych"],
    preventionTips: ["Bezpieczne ustawienia domyślne", "Ciągły skan konfiguracji chmury", "IAM najmniejszych uprawnień", "Alerty na zmiany publicznego dostępu"],
    relatedTopics: ["CSPM", "IAM", "Klasyfikacja danych", "Zarządzanie sekretami"],
  },
  {
    id: "tracking-cookies-and-fingerprinting",
    title: "Ciasteczka śledzące i fingerprinting",
    category: "privacy",
    readingTime: "4 min czytania",
    dangerLevel: "Low",
    description:
      "Śledzenie w sieci łączy ciasteczka i odciski przeglądarki, by budować trwałe profile zachowań między stronami.",
    howItWorks: ["Trackery stron trzecich ustawiają identyfikatory", "Fingerprinting używa atrybutów przeglądarki/urządzenia", "Profile łączone z ekosystemami reklam", "Dane wpływają na manipulację ukierunkowaną"],
    examples: ["Ten sam profil reklamowy na wielu stronach", "Profilowanie cieniem bez konta", "Śledzenie między urządzeniami przez wspólne ID"],
    redFlags: ["Mnóstwo skryptów stron trzecich", "Brak kontroli zgody", "Trwała personalizacja reklam", "Nieznani dostawcy analityki"],
    preventionTips: ["Ustawienia prywatności przeglądarki", "Blokada ciasteczek stron trzecich", "Rozszerzenia blokujące trackery", "Ograniczanie zbędnych tagów skryptowych"],
    relatedTopics: ["Prywatność online", "Brokerzy danych", "Bezpieczeństwo przeglądarki", "Zarządzanie zgodą"],
  },
  {
    id: "pretexting-attacks",
    title: "Ataki z pretekstem (pretexting)",
    category: "social-engineering",
    readingTime: "5 min czytania",
    dangerLevel: "High",
    description:
      "Pretexting wykorzystuje zmyślone scenariusze, by zdobyć zaufanie i skłonić ofiarę do ujawnienia informacji lub ryzykownych działań.",
    howItWorks: ["Budowa wiarygodnej tożsamości", "Biznesowy kontekst", "Prośba o poufne dane lub dostęp", "Presja autorytetu bez weryfikacji"],
    examples: ["Fałszywy audytor żądający list płac", "Podszyty dostawca zmieniający dane bankowe", "„Admin IT” proszący o kod OTP"],
    redFlags: ["Niezweryfikowane twierdzenia tożsamości", "Presja by ominąć procedury", "Wrażliwe żądania bez ticketu", "Brak oficjalnego kanału"],
    preventionTips: ["Lista kontrolna weryfikacji", "Wymagane udokumentowane akceptacje", "Szkolenia z inżynierii społecznej", "Eskalacja nietypowych próśb do zespołu bezpieczeństwa"],
    relatedTopics: ["Phishing", "Vishing", "Ryzyko insidera", "Świadomość bezpieczeństwa"],
  },
  {
    id: "network-monitoring-basics",
    title: "Podstawy monitorowania sieci",
    category: "network-security",
    readingTime: "6 min czytania",
    dangerLevel: "Medium",
    description:
      "Ciągła widoczność sieci pomaga wcześnie wykrywać ruch horyzontalny, C2 i nietypowe zachowania.",
    howItWorks: ["Zbieranie telemetrii przepływów i DNS", "Baseline normalnego ruchu", "Wykrywanie anomalii i podejrzanych beaconów", "Szybkie dochodzenie i izolacja"],
    examples: ["Nietypowe zapytania DNS w nocy", "Skanowanie sieci wewnętrznej z hosta", "Nieoczekiwany szyfrowany ruch do rzadkich celów"],
    redFlags: ["Brak scentralizowanych logów", "Brak widoczności east-west", "Brak detekcji anomalii", "Brak procesu triage alertów"],
    preventionTips: ["Scentralizowany SIEM", "Segmentacja aktywów krytycznych", "Ciągłe strojenie detekcji", "Regularne threat hunting"],
    relatedTopics: ["SOC", "Wykrywanie zagrożeń", "IR", "Segmentacja"],
  },
];
