import {
  BadgeAlert,
  Bot,
  Briefcase,
  Bug,
  Cloud,
  Fingerprint,
  Globe,
  Network,
  Radio,
  ServerCog,
  Shield,
  KeyRound,
  MailWarning,
  ScanSearch,
  ShieldCheck,
  Smartphone,
  Target,
  Workflow,
} from "lucide-react";
import type { WikiArticle, WikiCategory } from "@/types/wiki";

const wikiCategories: WikiCategory[] = [
  { id: "phishing", label: "Phishing", icon: MailWarning },
  { id: "password-security", label: "Password Security", icon: KeyRound },
  { id: "web-security", label: "Web Security", icon: Globe },
  { id: "malware", label: "Malware", icon: Bug },
  { id: "ai-threats", label: "AI Threats", icon: Bot },
  { id: "workplace-security", label: "Workplace Security", icon: Briefcase },
  { id: "mobile-security", label: "Mobile Security", icon: Smartphone },
  { id: "cloud-security", label: "Cloud Security", icon: Cloud },
  { id: "privacy", label: "Privacy", icon: ShieldCheck },
  { id: "social-engineering", label: "Social Engineering", icon: BadgeAlert },
  { id: "network-security", label: "Network Security", icon: Network },
  { id: "incident-response", label: "Incident Response", icon: Shield },
  { id: "identity-access", label: "Identity & Access", icon: Fingerprint },
  { id: "devsecops", label: "DevSecOps", icon: Workflow },
  { id: "email-security", label: "Email Security", icon: MailWarning },
  { id: "iot-security", label: "IoT Security", icon: Radio },
  { id: "endpoint-security", label: "Endpoint Security", icon: Smartphone },
  { id: "threat-intelligence", label: "Threat Intelligence", icon: ScanSearch },
  { id: "application-security", label: "Application Security", icon: ServerCog },
  { id: "cryptography", label: "Cryptography", icon: KeyRound },
  { id: "security-awareness", label: "Security Awareness", icon: Target },
];

const wikiArticles: WikiArticle[] = [
  {
    id: "what-is-phishing",
    title: "What is Phishing?",
    category: "phishing",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "Phishing is a social engineering attack where criminals impersonate trusted brands to steal passwords, payment details, or MFA codes.",
    howItWorks: ["Fake emails", "Fake login pages", "Social engineering pressure", "Urgent messages"],
    examples: [
      "Fake PayPal verification email",
      "Spoofed Microsoft 365 login page",
      "\"Your account will be suspended\" scam message",
    ],
    redFlags: ["Suspicious domains", "Spelling errors", "Urgent threats", "Unexpected attachments"],
    preventionTips: ["Verify sender identity", "Hover over links", "Use MFA", "Never share passwords"],
    relatedTopics: ["Spear phishing", "Smishing", "Business email compromise", "MFA best practices"],
  },
  {
    id: "password-security-fundamentals",
    title: "Password Security Fundamentals",
    category: "password-security",
    readingTime: "7 min read",
    dangerLevel: "Medium",
    description:
      "Strong unique passwords, password managers, and MFA are essential to block account takeovers and credential stuffing.",
    howItWorks: [
      "Attackers use leaked password dumps",
      "Bots test reused credentials at scale",
      "Weak passwords are cracked quickly",
      "MFA blocks many automated takeovers",
    ],
    examples: ["Weak password: password123", "Medium password: Summer2024!", "Strong password: Q7#fP2!mL9@t"],
    redFlags: ["Reused passwords", "No MFA", "No password manager", "Credentials shared over chat"],
    preventionTips: [
      "Use long unique passphrases",
      "Store secrets in a password manager",
      "Enable MFA on critical services",
      "Rotate compromised credentials immediately",
    ],
    relatedTopics: ["Credential stuffing", "Passkeys", "Session hijacking", "MFA fatigue"],
  },
  {
    id: "malware-overview",
    title: "Malware Overview",
    category: "malware",
    readingTime: "8 min read",
    dangerLevel: "Critical",
    description:
      "Malware is malicious software designed to steal data, spy on users, damage systems, or encrypt files for ransom.",
    howItWorks: ["Infection via email or download", "Payload execution", "Persistence mechanism", "Data theft or encryption"],
    examples: ["Ransomware locking company files", "Trojan hidden in cracked tools", "Spyware collecting browser sessions"],
    redFlags: [
      "Sudden performance drops",
      "Unknown startup applications",
      "Unexpected outbound traffic",
      "Files becoming inaccessible",
    ],
    preventionTips: ["Patch systems quickly", "Use endpoint protection", "Avoid untrusted executables", "Maintain offline backups"],
    relatedTopics: ["Ransomware response", "EDR", "Zero-day exploits", "Sandboxing"],
  },
  {
    id: "ai-scams-deepfakes",
    title: "AI Scams & Deepfakes",
    category: "ai-threats",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "AI-generated voices, videos, and messages can be used to impersonate trusted people and trigger fraud or data leakage.",
    howItWorks: [
      "Voice cloning from short audio clips",
      "Deepfake video impersonation",
      "AI-generated phishing messages",
      "Synthetic social identities",
    ],
    examples: [
      "Fake executive voice requesting urgent transfer",
      "Deepfake support call asking for OTP",
      "AI-generated HR email with malware attachment",
    ],
    redFlags: [
      "Unexpected urgency from familiar contacts",
      "Odd sentence structure or timing",
      "Payment process bypass requests",
      "No alternative verification path",
    ],
    preventionTips: [
      "Use callback verification",
      "Require dual approval for transfers",
      "Set internal emergency verification phrases",
      "Train teams on deepfake signals",
    ],
    relatedTopics: ["BEC", "Vishing", "Identity spoofing", "Fraud prevention controls"],
  },
  {
    id: "browser-security-basics",
    title: "Browser Security Basics",
    category: "web-security",
    readingTime: "6 min read",
    dangerLevel: "Medium",
    description:
      "Browsers are a major attack surface. Secure settings and extension hygiene reduce drive-by attacks and tracking abuse.",
    howItWorks: [
      "Malicious scripts run in browser contexts",
      "Unsafe extensions leak data",
      "Compromised sessions can be hijacked",
      "Phishing pages mimic trusted apps",
    ],
    examples: [
      "Extension requesting unnecessary permissions",
      "Session cookie theft from unsafe devices",
      "Malvertising redirect chains",
    ],
    redFlags: ["Unknown extensions", "Unexpected redirects", "Certificate warnings", "Auto-download prompts"],
    preventionTips: [
      "Keep browser updated",
      "Use trusted extensions only",
      "Enable safe browsing protections",
      "Avoid logging in on shared devices",
    ],
    relatedTopics: ["XSS", "Session security", "TLS", "Tracking prevention"],
  },
  {
    id: "remote-work-security",
    title: "Remote Work Security",
    category: "workplace-security",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "Distributed teams are targeted through weak endpoints, shadow IT, and phishing. Clear controls reduce enterprise exposure.",
    howItWorks: [
      "Compromised unmanaged devices",
      "Insecure home network access",
      "Credential theft on personal tools",
      "Unverified file sharing",
    ],
    examples: [
      "Sensitive docs shared through personal cloud",
      "VPN credentials phished by fake portal",
      "Open RDP exposed from home router",
    ],
    redFlags: ["Unknown devices", "No disk encryption", "Bypassed VPN", "Admin rights on daily accounts"],
    preventionTips: [
      "Enforce managed endpoints",
      "Use MFA and SSO",
      "Adopt least privilege",
      "Audit remote access continuously",
    ],
    relatedTopics: ["Zero trust", "Endpoint security", "Access governance", "Data loss prevention"],
  },
  {
    id: "mobile-phishing",
    title: "Mobile Phishing",
    category: "mobile-security",
    readingTime: "5 min read",
    dangerLevel: "High",
    description:
      "Attackers abuse SMS, messaging apps, and mobile notifications to steal credentials and one-time codes.",
    howItWorks: [
      "Fake delivery or banking SMS",
      "Malicious shortened links",
      "Fake app update prompts",
      "OTP harvesting flows",
    ],
    examples: [
      "Fake courier link requesting payment card",
      "Impersonated bank alert in messenger",
      "QR-code based login theft",
    ],
    redFlags: ["Short links", "Urgency in SMS", "Unexpected app install request", "MFA code requests"],
    preventionTips: [
      "Never trust links in unsolicited SMS",
      "Use official app stores only",
      "Enable SIM lock protections",
      "Report suspicious messages quickly",
    ],
    relatedTopics: ["Smishing", "SIM swap", "MFA security", "Mobile malware"],
  },
  {
    id: "cloud-shared-responsibility",
    title: "Cloud Shared Responsibility",
    category: "cloud-security",
    readingTime: "5 min read",
    dangerLevel: "Medium",
    description:
      "Cloud security is shared: providers secure infrastructure while customers secure identities, data, and configurations.",
    howItWorks: [
      "Provider secures physical/runtime layers",
      "Customer secures IAM and data access",
      "Misconfigurations expose cloud assets",
      "Weak keys enable lateral movement",
    ],
    examples: [
      "Public object storage leaking records",
      "Over-privileged service accounts",
      "Hardcoded cloud API keys in repos",
    ],
    redFlags: ["Public buckets", "No key rotation", "No audit logging", "Excessive admin roles"],
    preventionTips: [
      "Apply least privilege IAM",
      "Enable centralized audit trails",
      "Scan IaC for misconfigurations",
      "Rotate and vault secrets",
    ],
    relatedTopics: ["IAM", "CSPM", "Secrets management", "Data classification"],
  },
  {
    id: "online-privacy-basics",
    title: "Online Privacy Basics",
    category: "privacy",
    readingTime: "5 min read",
    dangerLevel: "Medium",
    description:
      "Digital privacy reduces identity theft and targeted fraud by limiting unnecessary data exposure online.",
    howItWorks: [
      "Trackers collect behavior across sites",
      "Data brokers aggregate personal records",
      "Oversharing reveals security answers",
      "Leaked metadata exposes habits",
    ],
    examples: [
      "Location metadata in uploaded photos",
      "Public profile revealing birth details",
      "Third-party trackers profiling behavior",
    ],
    redFlags: ["Broad app permissions", "Public personal details", "Unknown data brokers", "Persistent ad tracking"],
    preventionTips: [
      "Review privacy settings monthly",
      "Use browser anti-tracking controls",
      "Minimize personal data sharing",
      "Use unique emails for services",
    ],
    relatedTopics: ["Identity theft", "OSINT", "Tracker blocking", "Privacy laws"],
  },
  {
    id: "social-engineering-basics",
    title: "Social Engineering Basics",
    category: "social-engineering",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "Social engineering manipulates trust, fear, and urgency to bypass technical defenses through human behavior.",
    howItWorks: [
      "Build false trust quickly",
      "Trigger urgency/fear response",
      "Request sensitive action",
      "Exploit authority bias",
    ],
    examples: [
      "Impersonated IT support asking for reset code",
      "Fake executive requesting urgent transfer",
      "Tailgating into restricted office area",
    ],
    redFlags: ["Unusual urgency", "Bypassing process", "Identity mismatch", "Pressure to avoid verification"],
    preventionTips: [
      "Verify requests on separate channel",
      "Use strict approval workflows",
      "Train teams with simulations",
      "Reward reporting of suspicious behavior",
    ],
    relatedTopics: ["Phishing", "BEC", "Insider risk", "Security awareness"],
  },
  {
    id: "network-segmentation",
    title: "Network Segmentation",
    category: "network-security",
    readingTime: "7 min read",
    dangerLevel: "High",
    description:
      "Segmentation limits lateral movement after compromise by isolating systems, users, and services across trust zones.",
    howItWorks: [
      "Create security zones by sensitivity",
      "Apply strict east-west traffic policies",
      "Use firewall rules between segments",
      "Monitor unusual cross-segment traffic",
    ],
    examples: [
      "Isolating production databases from user VLANs",
      "Separate admin network for privileged access",
      "Guest Wi-Fi isolated from corporate services",
    ],
    redFlags: ["Flat network", "Broad allow-any rules", "Unmonitored internal traffic", "Shared admin paths"],
    preventionTips: [
      "Adopt zero-trust segmentation",
      "Use deny-by-default policies",
      "Review rules regularly",
      "Alert on suspicious lateral movement",
    ],
    relatedTopics: ["Firewall policy", "Zero trust", "NAC", "Lateral movement detection"],
  },
  {
    id: "incident-response-lifecycle",
    title: "Incident Response Lifecycle",
    category: "incident-response",
    readingTime: "8 min read",
    dangerLevel: "Critical",
    description:
      "A clear incident response lifecycle helps teams detect, contain, eradicate, and recover from cyber incidents quickly.",
    howItWorks: [
      "Preparation and runbooks",
      "Detection and triage",
      "Containment and eradication",
      "Recovery and lessons learned",
    ],
    examples: [
      "Ransomware outbreak containment",
      "Credential compromise investigation",
      "Cloud account takeover response",
    ],
    redFlags: ["No on-call process", "Missing runbooks", "Delayed escalation", "No post-incident review"],
    preventionTips: [
      "Practice tabletop exercises",
      "Define severity and ownership",
      "Centralize logs for triage",
      "Track corrective actions post-incident",
    ],
    relatedTopics: ["Forensics", "SOC operations", "Crisis communication", "BCP/DR"],
  },
  {
    id: "identity-access-management",
    title: "Identity & Access Management",
    category: "identity-access",
    readingTime: "7 min read",
    dangerLevel: "High",
    description:
      "IAM controls who can access systems and data. Strong identity governance is fundamental to modern security.",
    howItWorks: [
      "Authenticate users strongly",
      "Authorize least privilege access",
      "Review and revoke stale accounts",
      "Audit privileged activity continuously",
    ],
    examples: [
      "Admin account takeover from weak MFA",
      "Ex-employee account left active",
      "Service account with excessive permissions",
    ],
    redFlags: ["Shared accounts", "No access reviews", "Permanent admin rights", "No centralized SSO"],
    preventionTips: [
      "Use SSO and conditional access",
      "Enforce just-in-time privilege",
      "Automate joiner/mover/leaver flows",
      "Audit critical access paths",
    ],
    relatedTopics: ["PAM", "RBAC", "Zero trust access", "Identity governance"],
  },
  {
    id: "devsecops-foundations",
    title: "DevSecOps Foundations",
    category: "devsecops",
    readingTime: "7 min read",
    dangerLevel: "Medium",
    description:
      "DevSecOps integrates security into development and delivery pipelines so vulnerabilities are caught early.",
    howItWorks: [
      "Shift-left security testing",
      "Automated SAST/DAST in CI",
      "Dependency and secret scanning",
      "Policy checks for IaC",
    ],
    examples: [
      "Blocking merge on critical dependency CVE",
      "Detecting leaked API key in commit",
      "Failing deploy due to insecure IaC config",
    ],
    redFlags: ["No security checks in CI", "Unpinned dependencies", "Ignored critical findings", "Manual-only releases"],
    preventionTips: [
      "Automate security gates",
      "Treat findings as backlog items",
      "Use signed artifacts",
      "Continuously patch dependencies",
    ],
    relatedTopics: ["Supply chain security", "SAST", "DAST", "IaC security"],
  },
  {
    id: "email-authentication",
    title: "Email Authentication (SPF, DKIM, DMARC)",
    category: "email-security",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "Email authentication standards reduce spoofing risk and improve phishing resilience for organizational domains.",
    howItWorks: [
      "SPF validates sending servers",
      "DKIM signs message integrity",
      "DMARC defines enforcement policy",
      "Reports reveal spoofing attempts",
    ],
    examples: [
      "Spoofed domain blocked by DMARC reject",
      "Mailbox provider quarantining failed DKIM email",
      "Forensic reports showing brand abuse",
    ],
    redFlags: ["No DMARC policy", "Misaligned SPF/DKIM", "High spoofing report volume", "Untrusted third-party senders"],
    preventionTips: [
      "Publish SPF, DKIM, DMARC correctly",
      "Start DMARC in monitor mode then enforce",
      "Review aggregate reports weekly",
      "Inventory approved sending services",
    ],
    relatedTopics: ["Phishing prevention", "Brand protection", "Mail gateway security", "Domain hygiene"],
  },
  {
    id: "iot-device-hardening",
    title: "IoT Device Hardening",
    category: "iot-security",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "IoT devices often ship with weak defaults. Hardening and segmentation are key to reducing compromise risk.",
    howItWorks: [
      "Change default credentials immediately",
      "Patch firmware regularly",
      "Isolate IoT from critical networks",
      "Disable unnecessary services",
    ],
    examples: [
      "Camera botnet built from default passwords",
      "Smart sensor exploited via old firmware",
      "Insecure IoT admin panel exposed to internet",
    ],
    redFlags: ["Default passwords", "No firmware update path", "Internet-exposed device panels", "No network isolation"],
    preventionTips: [
      "Asset inventory for all IoT devices",
      "Dedicated VLAN for IoT",
      "Strong auth and certificate management",
      "Monitor anomalous IoT traffic",
    ],
    relatedTopics: ["OT security", "Network segmentation", "Asset management", "Firmware security"],
  },
  {
    id: "endpoint-protection-basics",
    title: "Endpoint Protection Basics",
    category: "endpoint-security",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "Endpoints are primary entry points for attacks. Layered protection and monitoring reduce compromise impact.",
    howItWorks: [
      "Monitor suspicious process behavior",
      "Enforce device hardening baselines",
      "Detect persistence mechanisms",
      "Isolate compromised hosts quickly",
    ],
    examples: [
      "Malicious script blocked by EDR policy",
      "Compromised laptop quarantined from network",
      "Unauthorized PowerShell activity alert",
    ],
    redFlags: ["Disabled endpoint agent", "Old OS patches", "Unknown binaries", "Unexpected admin tools"],
    preventionTips: [
      "Use EDR/XDR with centralized alerting",
      "Patch operating systems quickly",
      "Restrict local admin privileges",
      "Isolate high-risk devices from core assets",
    ],
    relatedTopics: ["EDR", "Device hardening", "Incident response", "Privilege management"],
  },
  {
    id: "threat-intel-fundamentals",
    title: "Threat Intelligence Fundamentals",
    category: "threat-intelligence",
    readingTime: "7 min read",
    dangerLevel: "Medium",
    description:
      "Threat intelligence helps teams understand attacker tactics and prioritize defenses based on real-world activity.",
    howItWorks: [
      "Collect indicators and adversary reports",
      "Correlate intel with internal telemetry",
      "Prioritize detections and mitigations",
      "Share relevant intelligence internally",
    ],
    examples: [
      "Blocking domains tied to active phishing kits",
      "Updating detections using current ransomware TTPs",
      "Alert tuning based on sector-specific campaigns",
    ],
    redFlags: ["Unverified intel feeds", "No context for indicators", "Outdated detection rules", "No feedback loop"],
    preventionTips: [
      "Use curated intel sources",
      "Map intel to MITRE ATT&CK techniques",
      "Automate IOC enrichment where possible",
      "Review intel impact in weekly security ops",
    ],
    relatedTopics: ["SOC operations", "Detection engineering", "MITRE ATT&CK", "CTI workflows"],
  },
  {
    id: "secure-coding-basics",
    title: "Secure Coding Basics",
    category: "application-security",
    readingTime: "7 min read",
    dangerLevel: "High",
    description:
      "Application security starts with secure coding patterns, input validation, and robust authentication/authorization.",
    howItWorks: [
      "Validate all untrusted input",
      "Use secure auth and session controls",
      "Apply least privilege in app services",
      "Test continuously for vulnerabilities",
    ],
    examples: [
      "Preventing SQL injection with parameterized queries",
      "Blocking XSS via output encoding",
      "Fixing insecure direct object references",
    ],
    redFlags: ["Hardcoded secrets", "Missing input validation", "Weak auth flows", "No security testing in CI"],
    preventionTips: [
      "Adopt secure coding standards",
      "Run SAST/DAST checks in pipeline",
      "Perform dependency vulnerability scanning",
      "Rotate and vault application secrets",
    ],
    relatedTopics: ["OWASP Top 10", "DevSecOps", "SAST", "Secrets management"],
  },
  {
    id: "encryption-basics",
    title: "Encryption Basics",
    category: "cryptography",
    readingTime: "6 min read",
    dangerLevel: "Medium",
    description:
      "Encryption protects confidentiality at rest and in transit. Correct key management is as important as algorithms.",
    howItWorks: [
      "Use symmetric encryption for data storage",
      "Use asymmetric cryptography for key exchange",
      "Protect data in transit with TLS",
      "Rotate and protect cryptographic keys",
    ],
    examples: [
      "Database field encryption for sensitive records",
      "TLS certificates securing API traffic",
      "Key rotation reducing blast radius after leaks",
    ],
    redFlags: ["Weak or deprecated ciphers", "Keys stored in source code", "Expired certificates", "No key rotation policy"],
    preventionTips: [
      "Use modern algorithms and TLS versions",
      "Store keys in dedicated secret managers",
      "Rotate certificates and keys regularly",
      "Encrypt backups and sensitive logs",
    ],
    relatedTopics: ["TLS", "PKI", "Key management", "Data protection"],
  },
  {
    id: "security-awareness-training",
    title: "Security Awareness Training",
    category: "security-awareness",
    readingTime: "5 min read",
    dangerLevel: "Medium",
    description:
      "Security awareness programs reduce human-risk incidents by teaching practical threat recognition and response habits.",
    howItWorks: [
      "Run role-based training modules",
      "Use phishing simulations regularly",
      "Reinforce habits with short refreshers",
      "Track behavior improvements over time",
    ],
    examples: [
      "Quarterly phishing simulation campaigns",
      "Micro-learning on password hygiene",
      "Incident reporting drills for non-technical teams",
    ],
    redFlags: ["One-time annual training", "No simulation exercises", "No reporting culture", "Training not role-specific"],
    preventionTips: [
      "Deliver short and frequent sessions",
      "Tailor material by department",
      "Reward early reporting of suspicious activity",
      "Measure outcomes, not completion only",
    ],
    relatedTopics: ["Phishing defense", "Social engineering", "Human risk management", "Security culture"],
  },
  {
    id: "spear-phishing-targeted-attacks",
    title: "Spear Phishing Attacks",
    category: "phishing",
    readingTime: "5 min read",
    dangerLevel: "High",
    description:
      "Spear phishing targets specific people with personalized lures to bypass generic awareness controls.",
    howItWorks: [
      "Attacker researches victim details",
      "Crafts personalized malicious message",
      "Uses urgency and trust signals",
      "Steals credentials or triggers malware",
    ],
    examples: [
      "Fake CFO email requesting urgent payment",
      "Personalized HR document link",
      "Vendor invoice spoof with real names",
    ],
    redFlags: ["Highly specific but unusual request", "Domain lookalikes", "Unexpected payment changes", "External login pages"],
    preventionTips: ["Verify through second channel", "Use payment approval controls", "Train high-risk teams", "Enable phishing-resistant MFA"],
    relatedTopics: ["BEC", "Social engineering", "Email security", "MFA"],
  },
  {
    id: "passkeys-passwordless-security",
    title: "Passkeys & Passwordless Security",
    category: "password-security",
    readingTime: "6 min read",
    dangerLevel: "Low",
    description:
      "Passkeys reduce phishing and credential theft by replacing traditional passwords with cryptographic authentication.",
    howItWorks: [
      "Device creates key pair",
      "Private key remains on device",
      "Authentication uses signed challenge",
      "No shared password secret transmitted",
    ],
    examples: [
      "Login with device biometrics",
      "Cross-device sign-in with QR flow",
      "Password reset volume reduction",
    ],
    redFlags: ["No account recovery controls", "Shared unmanaged devices", "Legacy-only login flows", "No MFA backup method"],
    preventionTips: ["Adopt passkeys on critical apps", "Keep secure recovery process", "Combine with device security", "Educate users on enrollment"],
    relatedTopics: ["FIDO2", "MFA", "Credential stuffing", "Identity security"],
  },
  {
    id: "xss-attack-overview",
    title: "Cross-Site Scripting (XSS) Overview",
    category: "web-security",
    readingTime: "7 min read",
    dangerLevel: "High",
    description:
      "XSS lets attackers inject scripts into trusted pages, enabling session theft, redirects, or malicious actions.",
    howItWorks: [
      "Unsanitized input reaches browser",
      "Injected script executes in user context",
      "Cookies/tokens may be exposed",
      "Attacker hijacks actions or sessions",
    ],
    examples: [
      "Comment field script injection",
      "Stored payload in profile bio",
      "Reflected script in search query",
    ],
    redFlags: ["Missing output encoding", "Unsafe HTML rendering", "Inline script-heavy pages", "No CSP policy"],
    preventionTips: ["Escape untrusted output", "Use CSP", "Validate and sanitize inputs", "Use secure frameworks defaults"],
    relatedTopics: ["OWASP Top 10", "Session hijacking", "CSP", "Secure coding"],
  },
  {
    id: "ransomware-attacks",
    title: "Ransomware Attacks",
    category: "malware",
    readingTime: "7 min read",
    dangerLevel: "Critical",
    description:
      "Ransomware encrypts files and demands payment, often after data theft and privilege escalation.",
    howItWorks: [
      "Initial access via phishing or exploit",
      "Privilege escalation and lateral movement",
      "Data exfiltration before encryption",
      "Encryption and extortion note delivery",
    ],
    examples: [
      "Domain-wide file server encryption",
      "Double extortion with leaked data threats",
      "Backup deletion before payload launch",
    ],
    redFlags: ["Mass file rename spikes", "Disabled security tools", "Unusual admin actions", "Ransom note artifacts"],
    preventionTips: ["Offline immutable backups", "Segmentation and least privilege", "Patch critical systems", "Practice incident response playbooks"],
    relatedTopics: ["Incident response", "EDR", "Backup strategy", "Network segmentation"],
  },
  {
    id: "deepfakes-explained",
    title: "Deepfakes Explained",
    category: "ai-threats",
    readingTime: "6 min read",
    dangerLevel: "High",
    description:
      "Deepfakes use AI to fabricate realistic media for fraud, impersonation, and disinformation campaigns.",
    howItWorks: [
      "Collect voice/video training samples",
      "Generate synthetic media output",
      "Embed in social or business context",
      "Exploit urgency to force action",
    ],
    examples: [
      "Fake executive approval video",
      "Cloned voice requesting wire transfer",
      "Synthetic identity used in support calls",
    ],
    redFlags: ["Lip-sync artifacts", "Inconsistent voice rhythm", "No verified callback path", "High-pressure requests"],
    preventionTips: ["Out-of-band verification", "Dual approval for payments", "Deepfake awareness training", "Use media provenance checks"],
    relatedTopics: ["Vishing", "Fraud prevention", "Identity spoofing", "Security awareness"],
  },
  {
    id: "least-privilege-access-model",
    title: "Least Privilege Access Model",
    category: "workplace-security",
    readingTime: "5 min read",
    dangerLevel: "Medium",
    description:
      "Least privilege limits user and service permissions to only what is needed, reducing blast radius of compromise.",
    howItWorks: [
      "Map required access by role",
      "Grant minimum permissions",
      "Review access on schedule",
      "Revoke unused privileges quickly",
    ],
    examples: [
      "Read-only access for analysts",
      "Temporary elevated admin roles",
      "Automatic access removal after project end",
    ],
    redFlags: ["Permanent admin rights", "Shared privileged accounts", "No access recertification", "Privilege creep"],
    preventionTips: ["Implement RBAC", "Use JIT privilege elevation", "Audit sensitive role assignments", "Automate joiner/mover/leaver workflows"],
    relatedTopics: ["IAM", "PAM", "Zero trust", "Insider risk"],
  },
  {
    id: "unsafe-mobile-apps",
    title: "Unsafe Mobile Apps",
    category: "mobile-security",
    readingTime: "5 min read",
    dangerLevel: "Medium",
    description:
      "Malicious or over-permissioned apps can exfiltrate sensitive data, track users, and weaken device security.",
    howItWorks: [
      "App requests excessive permissions",
      "Collects contacts/location/messages",
      "Sends data to remote servers",
      "May install hidden malicious modules",
    ],
    examples: [
      "Flashlight app requesting SMS access",
      "Fake banking app in third-party store",
      "Adware app with hidden background service",
    ],
    redFlags: ["Unnecessary permissions", "Unknown developer reputation", "Off-store APK install prompts", "Sudden battery/data drain"],
    preventionTips: ["Install from trusted stores only", "Review permissions carefully", "Keep mobile OS updated", "Use mobile threat protection"],
    relatedTopics: ["Mobile malware", "Smishing", "App permissions", "Device hardening"],
  },
  {
    id: "cloud-data-exposure",
    title: "Cloud Data Exposure",
    category: "cloud-security",
    readingTime: "5 min read",
    dangerLevel: "High",
    description:
      "Misconfigured cloud storage and identity policies are common causes of large-scale sensitive data leaks.",
    howItWorks: [
      "Public storage exposure by mistake",
      "Overly broad IAM permissions",
      "Leaked API keys in repositories",
      "Weak monitoring delays detection",
    ],
    examples: [
      "Public bucket containing customer PII",
      "Admin API key committed to source control",
      "Open snapshot exposing database dumps",
    ],
    redFlags: ["Public read/write resources", "No IAM guardrails", "No encryption enforcement", "Missing audit alerts"],
    preventionTips: ["Enforce secure defaults", "Scan cloud configs continuously", "Use least-privilege IAM", "Enable alerting for public exposure changes"],
    relatedTopics: ["CSPM", "IAM", "Data classification", "Secrets management"],
  },
  {
    id: "tracking-cookies-and-fingerprinting",
    title: "Tracking Cookies & Fingerprinting",
    category: "privacy",
    readingTime: "4 min read",
    dangerLevel: "Low",
    description:
      "Web tracking combines cookies and browser fingerprints to build persistent behavior profiles across websites.",
    howItWorks: [
      "Third-party trackers set identifiers",
      "Fingerprinting uses browser/device attributes",
      "Profiles are linked to ad ecosystems",
      "Behavior data influences targeted manipulation",
    ],
    examples: [
      "Same ad profile across multiple sites",
      "Shadow profiling without account login",
      "Cross-device tracking through shared identifiers",
    ],
    redFlags: ["Heavy third-party script usage", "No consent controls", "Persistent ad personalization", "Unknown analytics vendors"],
    preventionTips: ["Use privacy-focused browser settings", "Block third-party cookies", "Use tracker-blocking extensions", "Limit unnecessary script tags"],
    relatedTopics: ["Online privacy", "Data brokers", "Browser security", "Consent management"],
  },
  {
    id: "pretexting-attacks",
    title: "Pretexting Attacks",
    category: "social-engineering",
    readingTime: "5 min read",
    dangerLevel: "High",
    description:
      "Pretexting uses fabricated scenarios to gain trust and convince victims to share sensitive information or perform risky actions.",
    howItWorks: [
      "Attacker builds believable identity",
      "Creates plausible business context",
      "Requests confidential data or access",
      "Uses authority pressure to reduce verification",
    ],
    examples: [
      "Fake auditor requesting payroll records",
      "Impersonated vendor asking bank detail changes",
      "Pretend IT admin requesting OTP reset code",
    ],
    redFlags: ["Unverified identity claims", "Pressure to bypass procedures", "Sensitive requests without ticket trail", "No official communication channel"],
    preventionTips: ["Enforce verification checklist", "Require documented approvals", "Train on social engineering scenarios", "Escalate unusual requests to security team"],
    relatedTopics: ["Phishing", "Vishing", "Insider risk", "Security awareness"],
  },
  {
    id: "network-monitoring-basics",
    title: "Network Monitoring Basics",
    category: "network-security",
    readingTime: "6 min read",
    dangerLevel: "Medium",
    description:
      "Continuous network visibility helps detect lateral movement, command-and-control traffic, and anomalous behavior early.",
    howItWorks: [
      "Collect flow and DNS telemetry",
      "Baseline normal traffic behavior",
      "Detect anomalies and suspicious beacons",
      "Investigate and contain quickly",
    ],
    examples: [
      "Unusual outbound DNS queries at night",
      "Internal host scanning behavior",
      "Unexpected encrypted traffic to rare destinations",
    ],
    redFlags: ["No central logging", "Lack of east-west visibility", "No anomaly detection", "No alert triage process"],
    preventionTips: ["Centralize logs/SIEM", "Segment critical assets", "Tune detections continuously", "Run regular threat hunts"],
    relatedTopics: ["SOC", "Threat detection", "Incident response", "Segmentation"],
  },
];

export function getWikiCategories(): WikiCategory[] {
  return wikiCategories;
}

export function getWikiArticles(): WikiArticle[] {
  return wikiArticles;
}
